node_lines:
- node_line_name: retrieve_node_line
  nodes:
  - modules:
    - module_type: hybrid_rrf
      rrf_k: 10
      target_module_params: !!python/tuple
      - top_k: 3
      - embedding_batch: 256
        embedding_model: openai
        top_k: 3
      target_modules: !!python/tuple
      - bm25
      - vectordb
      top_k: 3
    node_type: retrieval
    strategy:
      metrics:
      - retrieval_f1
      - retrieval_recall
      - retrieval_precision
      - retrieval_ndcg
      - retrieval_map
      - retrieval_mrr
      speed_threshold: 10
